services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/python/Dockerfile
    restart: unless-stopped
    volumes:
      - ../:/workspaces:cached
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/postgres
    command: sleep infinity
    network_mode: service:db

  db:
    build:
      context: ..
      dockerfile: .devcontainer/postgresql/Dockerfile
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../:/workspaces:cached
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: platzimovies
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres-data:
