version: '3.8'

services:
  db:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../:/workspaces:cached
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dvdrental
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres-data:
